<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>en-US;en</SatelliteResourceLanguages>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
    <Version>1.0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ntk.Asterisk.Core\Ntk.Asterisk.Core.csproj" />
    <ProjectReference Include="..\Ntk.Asterisk.AMI\Ntk.Asterisk.AMI.csproj" />
    <ProjectReference Include="..\Ntk.Asterisk.ARI\Ntk.Asterisk.ARI.csproj" />
    <ProjectReference Include="..\Ntk.Asterisk.Monitoring\Ntk.Asterisk.Monitoring.csproj" />
    <ProjectReference Include="..\Ntk.Asterisk.Database\Ntk.Asterisk.Database.csproj" />
    <ProjectReference Include="..\..\Aspire\Ntk.Asterisk.ServiceDefaults\Ntk.Asterisk.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
