<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.5.3" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>ntk-asterisk-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DotNet\Ntk.Asterisk.WebApi\Ntk.Asterisk.WebApi.csproj" />
    <ProjectReference Include="..\..\WebPhone\Ntk.Asterisk.WebPhone\Ntk.Asterisk.WebPhone.csproj" />
    <ProjectReference Include="..\..\DotNet\Ntk.Asterisk.Console.AMI\Ntk.Asterisk.Console.AMI.csproj" />
    <ProjectReference Include="..\..\DotNet\Ntk.Asterisk.Console.ARI\Ntk.Asterisk.Console.ARI.csproj" />
    <ProjectReference Include="..\..\DotNet\Ntk.Asterisk.WinForm.AMI\Ntk.Asterisk.WinForm.AMI.csproj" />
    <ProjectReference Include="..\..\DotNet\Ntk.Asterisk.WinForm.ARI\Ntk.Asterisk.WinForm.ARI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.3" />
  </ItemGroup>
</Project>
