<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ntk.AsterNet.AMI\Ntk.AsterNet.AMI.csproj" />
		<ProjectReference Include="..\Ntk.Asterisk.Core\Ntk.Asterisk.Core.csproj" />
		<ProjectReference Include="..\Ntk.Asterisk.AMI\Ntk.Asterisk.AMI.csproj" />
		<ProjectReference Include="..\Ntk.Asterisk.Monitoring\Ntk.Asterisk.Monitoring.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
